- name: install expect module
  package:
    name: expect
  become: true

- name: "Keybase: encrypt test secrets"
  shell:
    keybase pgp encrypt -m "this is a decrypted test secret" | base64
  become_user: "{{ variable_user }}"
  register: pgp_secret_encrypted_temp
  ignore_errors: True
  when: "'keybase:' in pgp_public_key"

# It's not a bug, its a feature. https://stackoverflow.com/questions/34621799/ansible-how-do-i-avoid-registering-a-variable-when-a-when-condition-is-not
- set_fact:
    pgp_secret_encrypted: "{{pgp_secret_encrypted_temp.stdout | regex_escape() }}"
  when: pgp_secret_encrypted_temp.changed

- name: "GPG: encrypt test secrets"
  shell:
    echo "this is a decrypted test secret" | gpg -r "{{ pgp_email }}" --encrypt | base64
  become_user: "{{ variable_user }}"
  register: pgp_secret_encrypted_temp
  when: "'keybase:' not in pgp_public_key"

- set_fact:
    pgp_secret_encrypted: "{{pgp_secret_encrypted_temp.stdout | regex_escape()}}"
  when: pgp_secret_encrypted_temp.changed

- name: "debug pgp_secret_encrypted"
  debug:
    msg: "{{ pgp_secret_encrypted }}"

- name: Run expect to wait for a keybase pass and decrypt - first time is dirty output.
  shell: |
    test=$(keybase pgp encrypt -m "this is a decrypted test secret" | base64)
    /deployuser/scripts/pgp-expect-keybase.sh {{ keybase_secret | regex_escape() }} {{ pgp_secret_encrypted }}
  become_user: "{{ variable_user }}"
  connection: local
  no_log: true
  when: "'keybase:' in pgp_public_key"

- name: Run expect to wait for a keybase pass and decrypt - collect output.
  shell: |
    test=$(keybase pgp encrypt -m "this is a decrypted test secret" | base64)
    /deployuser/scripts/pgp-expect-keybase.sh {{ keybase_secret | regex_escape() }} {{ pgp_secret_encrypted }}
  become_user: "{{ variable_user }}"
  connection: local
  register: pgp_secret_output_temp
  no_log: true
  when: "'keybase:' in pgp_public_key"

- set_fact:
    pgp_secret_output: "{{pgp_secret_output_temp.stdout }}"
  when: pgp_secret_output_temp.changed

- name: "GPG: decrypt inline - collect output."
  shell: |
    echo {{ pgp_secret_encrypted }} | base64 --decode | gpg -dq --no-tty --passphrase {{ pgp_secret | regex_escape() }} --no-use-agent
  become_user: "{{ variable_user }}"
  connection: local
  register: pgp_secret_output_temp
  no_log: true
  failed_when: >
    ("base64: invalid input" in pgp_secret_output_temp.stderr) or
    (pgp_secret_output_temp.stderr != '')
  when: "'keybase:' not in pgp_public_key"

- set_fact:
    pgp_secret_output: "{{pgp_secret_output_temp.stdout}}"
  when: pgp_secret_output_temp.changed

- name: Test debug
  debug:
    var: pgp_secret_output

- name: Test if encryption failed
  fail:
    msg: The encryption and decryption test failed.
  when: pgp_secret_output != 'this is a decrypted test secret'

- name: Test passed if text 'this is a decrypted test secret' is readable in output.
  debug:
    var: pgp_secret_output
  when: pgp_secret_output == 'this is a decrypted test secret'