---
# tasks file for openvpn_package

# for some reason ansible struggles with this on the open vpn ami.  it can be tested at a later date with newer versions of ansible and py3
# - name: Add apt repo - openvpn - ubuntu # https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos
#   apt_key:
#     url: https://swupdate.openvpn.net/repos/repo-public.gpg
#     state: present
#   become: true

# Instead we use this method:

# - name: Update and upgrade apt packages
#   apt:
#     upgrade: yes
#     update_cache: yes
#     cache_valid_time: 86400 #One day
#   become: true

- name: Download apt gpt key for opevn vpn
  get_url: 
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
    dest: /tmp/openvpn.gpg
    mode: '0644'
  become: true
  connection: local # aquiring the key on the aws vpn ami has problems

- name: ensure permissions are correct
  file:
    path: /tmp/openvpn.gpg
    mode: '0644'
  become: true
  connection: local

- name: Copy gpg key
  copy: 
    src: /tmp/openvpn.gpg
    dest: /tmp/openvpn.gpg
    mode: '0644'
  become: yes

- name: install vpn key
  apt_key:
    file: /tmp/openvpn.gpg
    state: present
  become: true

- name: Add apt repo - /etc/apt/sources.list.d/openvpn-aptrepo.list
  apt_repository:
    repo: deb http://build.openvpn.net/debian/openvpn/release/2.4 xenial main
    filename: openvpn-aptrepo
    mode: '0644'
    state: present
  become: true

- name: install latest open vpn package
  package:
    name:
    - openvpn
    update_cache: yes
  become: true