---
# tasks file for roles/init-packages

- name: Collect some facts only for ansible_distribution
  setup:
    gather_subset:
      - '!all'
      - 'min'
  tags:
  - always
  
- name: ansible distro
  debug:
    var: ansible_distribution

- name: fping
  apt:
    name:
    - fping # used to ping with max reytries up to a certain time to test open vpn.
    state: present
    update_cache: yes
  register: install_package
  until: install_package is not failed
  retries: 5
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install mkpasswd, pip, pexpect, passlib, fping
  package:
    name:
    - python-pip
    - python-apt
    - whois
    - python-passlib
    - zip
    - openvpn
    - rng-tools
    - gpgv2
    - jq
    - inotify # Used to catch existance of interrupt file https://stackoverflow.com/questions/18893283/how-to-proceed-in-the-script-if-file-exists
    state: present
  become: true

- name: Install requests module to query web pages in (houdini python install script)
  pip:
    name: requests
    executable: pip
  become: true

- name: install pexpect for rhel / centos,
  pip:
    name: pexpect
    executable: pip
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

# Enterprise Linux'
# Above is for RHEL and Centos, the following is for Debian/Ubuntu:

- name: Install expect pip for Ubuntu
  pip:
    name: pexpect
    executable: pip
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install pexpect for ubuntu
  package:
    name:
    # - python-pexpect
    - nfs-common
    state: present
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'