- name: init ubl licence info if first time install
  shell: | 
    cd /opt/Thinkbox/DeadlineDatabase10/mongo/application/bin/
    ./deadline_mongo --sslPEMKeyPassword "{{ deadline_proxy_certificate_password }}" --eval 'db.DeadlineSettings.insert({"_id": "deadline_network_settings"},{$set:{UsageBasedURL: "{{ usage_based_url }}"}})'
    ./deadline_mongo --sslPEMKeyPassword "{{ deadline_proxy_certificate_password }}" --eval 'db.DeadlineSettings.insert({"_id": "deadline_network_settings"},{$set:{UsageBasedActivationCode: "{{ usage_based_activation_code }}"}})'
  when: ubl
  no_log: true
  become: true
  register: deadline_ubl

- debug:
    msg:  "{{ deadline_ubl.stdout }}"
  when: ubl

- name: update ubl licence info if already installed
  shell: |
    cd /opt/Thinkbox/DeadlineDatabase10/mongo/application/bin/
    ./deadline_mongo --sslPEMKeyPassword "{{ deadline_proxy_certificate_password }}" --eval 'db.DeadlineSettings.update({"_id": "deadline_network_settings"},{$set:{UsageBasedURL: "{{ usage_based_url }}"}})'
    ./deadline_mongo --sslPEMKeyPassword "{{ deadline_proxy_certificate_password }}" --eval 'db.DeadlineSettings.update({"_id": "deadline_network_settings"},{$set:{UsageBasedActivationCode: "{{ usage_based_activation_code }}"}})'
  when: ubl
  no_log: true
  become: true
  register: deadline_ubl

- debug:
    msg:  "{{ deadline_ubl.stdout }}"
  when: ubl