---
#tasks file for roles/aws-cli
- name: install the package, force upgrade
  pip: 
    name: pip
    extra_args: --upgrade
  become: true

- name: install the package for root, force upgrade
  pip: 
    name: awscli
    extra_args: --upgrade
  become_user: root

- name: install the package for user, force upgrade
  pip: 
    name: awscli
    extra_args: --upgrade --user
  become_user: "{{ variable_user }}"
  become: true

- name: install python-boto package
  package:
    name: python-boto
  become: true
  vars:
    ansible_python_interpreter: "{{ package_python_interpreter }}"


- name: install pip boto3
  pip:
    name: boto3
  become: true

- name: Case insensitive password string match for aws configure
  expect:
    command: /usr/local/bin/aws configure
    #/home/{{ variable_user }}/.local/bin/aws configure
    responses:
      .*Access Key ID \[.*\]: "{{ AWS_ACCESS_KEY }}"
      .*Secret Access Key \[.*\]: "{{ AWS_SECRET_KEY }}"
      .*region name \[.*\]: "{{ aws_region }}"
      .*output format \[.*\]: json
  become_user: "{{ variable_user }}"
  # you don't want to show passwords in your logs
  no_log: true