- name: Configure hserver
  debug:
    msg: Configure hserver address to license server ip

- name: set hserver ip for nodes to aquire licenses from for items in list
  include: houdini-set-hserver.yml
  loop: "{{ houdini_version_list }}"
  loop_control:
    loop_var: houdini_version_item
  when: houdini_install_type != "server" and houdini_license_server_address != "none"