---
# tasks file for ./ansible/roles/pip
# these packages are required to pass an encrypted string via commandline into a user pass and are suited to centos, and also for aws cli.

- name: Collect some facts only for ansible_distribution
  setup:
    gather_subset:
      - '!all'
      - 'min'
    gather_timeout: 60
  tags:
  - always

- name: Add epel repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: "{{ epel_repo_url }}"
    gpgkey: "{{ epel_repo_gpg_key_url }}"
    enabled: yes
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  tags:
  - add-epel

- name: hold linux-image-generic on vagrant as it breaks vagrant mounts currently preventing the image from booting
  command: echo "linux-image-generic hold" | dpkg --set-selections
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: hold linux-image-generic on vagrant as it breaks vagrant mounts currently preventing the image from booting
  command: apt-mark hold linux-image-generic
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Upgrade all yum packages except VirtualBox - to update virtual box run 'yum update' with no VM's running.
  yum:
    name: '*'
    state: latest
    exclude: VirtualBox # exclude virtualbox - if the entire pipe is running on a single host, it isn't possibel to update virtual box since it is being used during execution of this script.
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  vars:
    ansible_python_interpreter: /usr/bin/python2.7 # python 3 is not compatibale with the yum module
  tags:
  - upgrade-packages

# beware if mount issues arise, this may be related - https://askubuntu.com/questions/601/the-following-packages-have-been-kept-back-why-and-how-do-i-solve-it
- name: Upgrade all apt packages
  apt:
    name: "*"
    state: latest
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - upgrade-packages

- name: "install epel-release {{ package_python_interpreter }}"
  package:
    name: epel-release
    state: latest
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  vars:
    ansible_python_interpreter: "{{ package_python_interpreter }}"

- name: install pip
  package:
    name:
    - python-pip
    - python3-pip
    state: latest
  become: true
  vars:
    ansible_python_interpreter: "{{ package_python_interpreter }}"

- name: upgrade pip - ubuntu
  pip: 
    name: pip
    extra_args: --upgrade
    # executable: pip3.5
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  vars:
    ansible_python_interpreter: "{{ package_python_interpreter }}"
  tags:
    - upgrade-pip

- name: upgrade pip - centos
  pip: 
    name: pip
    extra_args: --upgrade
    # executable: pip3.6
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  vars:
    ansible_python_interpreter: "{{ package_python_interpreter }}"
  tags:
    - upgrade-pip

# - name: upgrade pip3
#   pip: 
#     name: pip
#     extra_args: --upgrade
#     executable: /bin/pip3.6
#   become: true
#   tags:
#     - upgrade-pip

- name: upgrade pyopenssl
  pip: 
    name: pyopenssl
    extra_args: --upgrade
  vars:
    ansible_python_interpreter: "{{ package_python_interpreter }}"
  become: true

# may break ubuntu in vagrant.
- name: remove cryptography and reinstall to fix a bug with boto and pip.
  pip: 
    name: cryptography
    state: absent
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: upgrade cryptography
  pip: 
    name: cryptography
    extra_args: --upgrade
  become: true

- name: upgrade paramiko to fix a bug with boto and pip
  pip: 
    name: paramiko
    extra_args: --upgrade
  become: true

- name: install pexpect
  pip:
    name: pexpect
  become: yes

- name: install idna
  pip:
    name: idna
  become: yes
  
- name: install passlib
  pip:
    name: passlib
  become: yes

- name: install requests
  pip:
    name: requests
  become: yes

- name: install wheel
  pip: 
    name: wheel
  become: true

# - name: uninstall urllib3 because of conflict with rhel 8 packages
#   pip:
#     name: urllib3
#     state: absent
#   become: yes
#   when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

# # consider removing -  unpacking of archive failed on file /usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname

# - name: Remove file - due to intermittent bug with urllib 3 install
#   file:
#     path: /usr/lib/python2.7/site-packages/urllib3/packages/ssl_match_hostname
#     state: absent
#   become: yes
#   changed_when: false
#   when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  
# - name: install python-urllib3 package - for some reason, installing, uninstalling, reinstalling fixes isues with boto3 install.
#   package:
#     name: 'python-urllib3'
#     state: present
#   become: yes
#   when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: install boto
  pip: 
    name: boto
    extra_args: --no-cache-dir -U
  become: true

- name: install boto3
  pip: 
    name: boto3
    extra_args: --no-cache-dir -U
  become: true