---
- hosts: "{{ variable_host | default('ansible_control') }}"
  remote_user: "{{ variable_user | default('deployuser') }}"
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become: true
  
  vars:
    ami_name: "softnas_ami"
    instance_id: ""
    description: ""

  roles:
    - role: aws-ami