---
- hosts: "{{ variable_host | default('firehawkgateway') }}"
  remote_user: "{{ variable_connect_as_user | default('deployuser') }}"
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become: true
  any_errors_fatal: true

  vars:
    my_password: "{{ user_deadlineuser_pw }}"
    no_extension: "{{ deadline_linux_installers_tar | splitext | first }}"
    basename: "{{ no_extension.split('/')[-1] }}"
    houdini_major_version: 18.0
    ubl: true
    
  roles:
    - role: s3-bucket
    - {role: deadlinedb, tags: 'deadlinedb'}
    