---
- hosts: "{{ variable_host | default('firehawkgateway') }}"
  remote_user: "{{ variable_connect_as_user | default('deployuser') }}"
  become: true

  # set permissions on dealine repository so that scripts can be copied by the deployuser user.
  pre_tasks:
  - include_role:
      name: deadline-db-check

  - name: copy deadline event to repository
    copy:
      src: /deployuser/scripts/deadline/SlaveAutoconf
      dest: /opt/Thinkbox/DeadlineRepository10/events
      owner: deadlineuser
      group: syscontrol
      mode: u+rX-w,g=rX-w,o-rwx
      force: true
      directory_mode: true
    become: true

  - file:
      path: /opt/Thinkbox/DeadlineRepository10/events/SlaveAutoconf
      mode: u+rX-w,g=rX-w,o-rwx
      recurse: true

  - include_role:
      name: deadline-db-check