- hosts: "{{ variable_host | default('ansible_control') }}"
  remote_user: "{{ variable_user | default('deployuser') }}"
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become: true

  vars:
    source: '/var/log/cloud-init-output.log'
    dest: 'firehawk/tmp/'
  
  tasks:
  - name: show dir contents
    shell: |
      dir=$(dirname "{{ source }}")
      ls -ltriah $dir
    become: true

  - name: "Get file {{ source }} copy to {{ dest }}"
    fetch:
      src: "{{ source }}"
      dest: "{{ dest }}"
      flat: yes
    become: true