- hosts: localhost
  gather_facts: "{{ variable_gather_facts | default('true') }}"
  # become: true

  vars:
    key_name: .vault-key-{{ envtier }}
    repo_dir: "{{ playbook_dir.split('/')[0:-1]|join('/') }}"
    key_folder: "{{ repo_dir }}/../secrets/keys/"
    key_path: "{{ repo_dir }}/../secrets/keys/{{ key_name }}"
    secret_path: "{{ repo_dir }}/../secrets-{{ envtier }}"

  pre_tasks:
    - debug:
        msg: "key_path = {{ key_path }}"

  # we have to ensure a blank key pass exists before starting.  we check if the file is blank before generating a key.
  # once a key is generated, the vaildate-encryption role will ensure the secrets file is encrypted with it

  roles:
    - init-keys-touch
    - init-keys
    # after keys are validated, then we encrypt the secrets file.
    - validate-encryption