---
- hosts: "{{ variable_host | default('ansible_control') }}"
  remote_user: "{{ variable_user | default('deployuser') }}"
  gather_facts: "{{ variable_gather_facts | default('true') }}"
  become: true

  roles:
    - role: init-packages