---
- hosts: "{{ variable_host | default('ansible_control') }}"
  remote_user: "{{ variable_user | default('deployuser') }}"
  gather_facts: "{{ variable_gather_facts | default('true') }}"
  become: true

  tasks:
    - name: test local connection.
      debug:
        msg: "test local connection"

- hosts: "{{ variable_host | default('ansible_control') }}"
  remote_user: "{{ variable_user | default('deployuser') }}"
  gather_facts: "{{ variable_gather_facts | default('true') }}"
  become: true

  vars:
    configure_gateway: false
    set_hostname: "{{ openfirehawkserver_name if not configure_gateway else 'gateway' }}"
    
  pre_tasks:
    - name: ensure source ./update_vars.sh initialised
      fail:
        msg: "A tier has not been defined. ensure you run 'source ./update_vars.sh --dev' or 'source ./update_vars.sh --prod' from the path /deployuser"
      when: envtier is not defined

  roles:
    - {role: 'init-host', tags: 'init-host'}
    - role: pip
    - role: init-packages
    - role: terraform
    - role: aws-cli

- hosts: "{{ variable_host | default('ansible_control') }}"
  remote_user: "{{ variable_user | default('deployuser') }}"
  gather_facts: "{{ variable_gather_facts | default('true') }}"
  become: true

  tasks:
    - name: Test connection.  Bad mounts may break local connection
      debug:
        msg: "test connection"