- hosts: ansible_control
  gather_facts: "{{ variable_gather_facts | default('true') }}"
  become: true

  tasks:

  - name: Kill SSH because otherwise the user will not be added to the group.
    shell: sleep 1; pkill -u {{ ansible_user }} sshd
    async: 3
    poll: 2
    tags:
    - onsite-install

  - name: reset ssh connection to allow user changes to affect 'current login user'
    meta: reset_connection