# This script will install ffmpeg

# Example install on an aws instance
# ansible-playbook -i ansible/inventory ansible/node-centos-ffmpeg.yaml -v --extra-vars "variable_host=role_workstation_centos hostname=cloud_workstation1.${var.public_domain_name}"
# Example local install on a RHEL 7.6 / CENTOS workstation / render node.
# ansible-playbook -i ansible/inventory ansible/node-centos-ffmpeg.yaml -v --extra-vars "variable_host=workstation1 variable_user=deadlineuser hostname=workstation1 ansible_become_pass=sompass"

- hosts: "{{ variable_host | default('role_node_centos') }}"
  remote_user: "{{ variable_connect_as_user | default('centos') }}"
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become: true

  vars:
    ansible_become_pass: "{{ user_deadlineuser_pw }}"

  tasks:
  - name: test connection
    debug:
      msg: "connection established"

- hosts: "{{ variable_host | default('role_node_centos') }}"
  remote_user: "{{ variable_connect_as_user | default('centos') }}"
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become: true

  vars:
    ansible_become_pass: "{{ user_deadlineuser_pw }}"
    variable_user: centos
    bastionip: "{{ groups['bastionip'][0] }}"
    skip_packages: false
    houdini_install_type: node
    bucket: "{{ installers_bucket }}"

  roles:
  - role: pip

  post_tasks:
  - name: Remote RPM install with yum
    yum:
      name: https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm

  - name: Remote RPM install with yum
    yum:
      name: https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-7.noarch.rpm

  - name: Install ffmpeg packages
    package:
      name: "{{ item }}"
      state: present
    when: not skip_packages
    with_items:
      - ffmpeg 
      - ffmpeg-devel