---
# tasks file for ansible/roles/init-keys

# The purpose of this module is to initialise a random key password if it doesn't exist.  No data in /keys is commited to source control.  Backup keys elsewhere.

- set_fact:
    key_contents: "{{lookup('file', '{{ key_path }}') }}"

- debug:
    msg: "vault key is empty: {{ key_contents }}"
  when: key_contents == ''

- set_fact:
    key_test: false
  when: key_contents == ''

- set_fact:
    key_test: true
  when: key_contents != ''

- name: notify
  debug:
    msg: "A new random key will be generated in  ../../secrets/keys/{{ key_name }}.  It will not be kept in version control, but it will be used to encrypt anything in  ../../secrets/ which are kept in version control.  It is important you store this key safely because if lost you will not have access to any secrets that define your current infrastructure state."
  when: key_test == false

- name: generate primary password for crypt
  copy:
    content: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters') }}"
    dest: "{{ key_path }}"
  when: key_test == false

# check key contents again, it should pass
- set_fact:
    key_contents: "{{lookup('file', '{{ key_path }}') }}"

- name: problem generating key
  failed_when: key_contents == ''
  fail: "vault key is empty: {{ key_contents }}"

- set_fact:
    key_test: false
  when: key_contents == ''

- set_fact:
    key_test: true
  when: key_contents != ''

- name: set key permissions to read only
  file:
    path: "{{ key_path }}"
    mode: 0400
    state: touch
    access_time: preserve
    modification_time: preserve
  become: true
  when: key_test == true